fix: correct binding & name of contract functions
Function Binding
----------------

When passing around contract functions throughout an app, I have ended
up in situations where `near-api-js` ends up throwing an error:

    TypeError: Cannot read property 'account' of undefined

Using arrow functions ensures correct binding of these functions, so
that `this` refers to what we expect.

`.name` behavior
----------------

If you call `someFunction.name`, JavaScript will show the name of the
function (see [mdn]). However, this doesn't work as expected with
functions defined using `Object.defineProperty`.

Using an approach found on [StackOverflow], this ensures that the
`.name` property works as expected for these contract functions.
Example:

    const contract = await new Contract(account, contractName, {
      viewMethods: ['getMessages']
    })
    console.log(conract.getMessages.name) // => 'getMessages'

  [mdn]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name
  [StackOverflow]: https://stackoverflow.com/a/41854075/249801

Other goodies
-------------

This also removes some tests from test/account.test.js, since these were
tests of Contract and there is a dedicated file for contract tests now